/**
 * AI Widget Showcase Website — Comprehensive 100% i18n & RTL Manager.
 */
const translations = {
  fr: {
    "nav.features": "Fonctionnalités",
    "nav.preview": "Aperçu",
    "nav.download": "Télécharger",
    "nav.getApp": "Télécharger",
    "hero.tag": "100% Hors-Ligne & Données Sécurisées",
    "hero.title": "L'Intelligence Artificielle <br /><span class='gradient-text'>Directement sur votre Bureau</span>",
    "hero.subtitle": "Un widget discret, ultra-rapide et tout-en-un. Chattez avec vos modèles LLM locaux, analysez vos devis Excel et documents PDF en un clin d'œil, recherchez sur le Web sans hallucination, et pilotez tout à la voix.",
    "hero.downloadExe": "Télécharger pour Windows",
    "hero.downloadExeSub": "Setup.exe · 8.9 Mo · Gratuit",
    "hero.otherVersions": "Autres formats",
    "hero.otherVersionsSub": "MSI Entreprise & Portable",
    "stats.ram": "Consommation RAM",
    "stats.privacy": "Confidentialité locale",
    "stats.latency": "Latence cloud",
    "mockup.title": "AI Widget — Mode Étendu (ChatGPT-Style)",
    "mockup.badge": "✓ Modèle Qwen 2.5 Local Actif",
    "mockup.userChip": "📎 Devis 40 logts.xlsx (XLSX)",
    "mockup.userMsg": "Peux-tu extraire le montant total HT et TTC de ce devis Excel ?",
    "mockup.botIntro": "Voici la synthèse financière extraite du tableau Excel joint :",
    "mockup.th1": "Désignation",
    "mockup.th2": "Montant HT",
    "mockup.th3": "Taux TVA",
    "mockup.th4": "Total TTC",
    "mockup.row1_desc": "Lot Gros Œuvre",
    "mockup.row2_desc": "Lot Électricité & CVC",
    "mockup.total_label": "MONTANT GLOBAL",
    "features.title": "Pourquoi choisir AI Widget ?",
    "features.desc": "Une suite d'outils ultra-puissants intégrés dans une interface ergonomique et intuitive.",
    "f1.title": "100% Local & Zéro Fuite",
    "f1.desc": "Vos documents, données et conversations ne quittent jamais votre machine. Fonctionne sans connexion Internet.",
    "f2.title": "Analyse Excel & PDF Universelle",
    "f2.desc": "Glissez vos fichiers .xlsx, .docx, .pdf ou scans OCR. L'IA extrait les tableaux, calcule les sommes et résume vos dossiers.",
    "f3.title": "Recherche Web Anti-Hallucination",
    "f3.desc": "Routeur d'intention intelligent qui recherche les faits publics en temps réel avec citation exacte des sources fiables.",
    "f4.title": "Chat Vocal Whisper & TTS",
    "f4.desc": "Parlez naturellement à votre assistant avec Whisper local et écoutez ses réponses avec des voix neuronales ultra-réalistes.",
    "f5.title": "Diagrammes Mermaid & LaTeX",
    "f5.desc": "Rendu vectoriel direct de formules mathématiques complexes et de diagrammes de flux interactifs.",
    "f6.title": "Licence & Multi-Profils Sécurisés",
    "f6.desc": "Gestion des profils isolés, chiffrement SQLite local et activation à vie sans abonnement mensuel.",
    "download.title": "Télécharger AI Widget pour Windows",
    "download.desc": "Compatible Windows 10 & Windows 11 (64-bit). Sans dépendance lourde.",
    "download.recommended": "Recommandé",
    "download.setupTitle": "Installateur Standard",
    "download.setupDesc": "Installation automatique avec raccourcis bureau et menu démarrer.",
    "download.btnExe": "📥 Télécharger (.exe)",
    "download.msiTitle": "Pack Entreprise (MSI)",
    "download.msiDesc": "Idéal pour les administrateurs système et déploiements réseau (GPO / SCCM).",
    "download.btnMsi": "📦 Télécharger (.msi)",
    "download.portableTitle": "Version Portable",
    "download.portableDesc": "Exécutable autonome sans aucune installation requise. Clé USB ready.",
    "download.btnPortable": "📂 Télécharger Portable",
    "footer.tagline": "Conçu avec passion par <strong>S.H.A dev</strong>. Tous droits réservés 2026.",
    "footer.contact": "📧 Support & Contact : s.h.a.dev.pro@gmail.com"
  },
  en: {
    "nav.features": "Features",
    "nav.preview": "Preview",
    "nav.download": "Download",
    "nav.getApp": "Download",
    "hero.tag": "100% Offline & Private AI",
    "hero.title": "Artificial Intelligence <br /><span class='gradient-text'>Directly on your Desktop</span>",
    "hero.subtitle": "A discrete, lightning-fast all-in-one desktop assistant. Chat with local LLMs, analyze Excel spreadsheets and PDFs instantly, browse the web with zero hallucinations, and control everything by voice.",
    "hero.downloadExe": "Download for Windows",
    "hero.downloadExeSub": "Setup.exe · 8.9 MB · Free",
    "hero.otherVersions": "Other Formats",
    "hero.otherVersionsSub": "Enterprise MSI & Portable",
    "stats.ram": "RAM Footprint",
    "stats.privacy": "Local Privacy",
    "stats.latency": "Cloud Latency",
    "mockup.title": "AI Widget — Expanded Mode (ChatGPT-Style)",
    "mockup.badge": "✓ Active Local Qwen 2.5 Model",
    "mockup.userChip": "📎 Construction Quote 40 Units.xlsx (XLSX)",
    "mockup.userMsg": "Can you extract total pre-tax and tax-included amounts from this Excel estimate?",
    "mockup.botIntro": "Here is the financial breakdown extracted from the attached spreadsheet:",
    "mockup.th1": "Designation",
    "mockup.th2": "Pre-Tax Amount",
    "mockup.th3": "VAT Rate",
    "mockup.th4": "Total Incl. Tax",
    "mockup.row1_desc": "Structural Works Lot",
    "mockup.row2_desc": "Electrical & HVAC Lot",
    "mockup.total_label": "OVERALL TOTAL",
    "features.title": "Why Choose AI Widget?",
    "features.desc": "A powerful local AI workspace designed for daily professional productivity.",
    "f1.title": "100% Local & Zero Data Leak",
    "f1.desc": "Your documents, prompts, and chats never leave your machine. Works completely offline.",
    "f2.title": "Universal Excel & PDF Analysis",
    "f2.desc": "Drag and drop .xlsx, .docx, .pdf or OCR scans. AI extracts tables, sums figures and drafts summaries.",
    "f3.title": "Anti-Hallucination Web Search",
    "f3.desc": "Smart intent classifier that fetches verified real-time public facts with cited sources.",
    "f4.title": "Whisper & Neural Voice Chat",
    "f4.desc": "Speak naturally with built-in local Whisper speech recognition and listen to neural voices.",
    "f5.title": "Mermaid & LaTeX Rendering",
    "f5.desc": "Instant vector rendering of complex math formulas and interactive workflow diagrams.",
    "f6.title": "Secure Profiles & Lifetime License",
    "f6.desc": "Isolated user workspaces, encrypted SQLite storage and lifetime activation with zero subscriptions.",
    "download.title": "Download AI Widget for Windows",
    "download.desc": "Compatible with Windows 10 & Windows 11 (64-bit). Ultra-lightweight.",
    "download.recommended": "Recommended",
    "download.setupTitle": "Standard Installer",
    "download.setupDesc": "Automatic setup with desktop and start menu shortcuts.",
    "download.btnExe": "📥 Download (.exe)",
    "download.msiTitle": "Enterprise Package (MSI)",
    "download.msiDesc": "Ideal for system administrators and corporate deployments (GPO / SCCM).",
    "download.btnMsi": "📦 Download (.msi)",
    "download.portableTitle": "Portable Edition",
    "download.portableDesc": "Standalone executable with zero installation needed. USB flash drive ready.",
    "download.btnPortable": "📂 Download Portable",
    "footer.tagline": "Built with passion by <strong>S.H.A dev</strong>. All rights reserved 2026.",
    "footer.contact": "📧 Support & Inquiries: s.h.a.dev.pro@gmail.com"
  },
  ar: {
    "nav.features": "المميزات",
    "nav.preview": "معاينة",
    "nav.download": "تحميل",
    "nav.getApp": "تحميل التطبيق",
    "hero.tag": "100% محلي وبدون إنترنت وحماية تامة",
    "hero.title": "الذكاء الاصطناعي الخارق <br /><span class='gradient-text'>مباشرة على سطح مكتبك</span>",
    "hero.subtitle": "أداة سطح مكتب أنيقة وسريعة للغاية. تحدث مع نماذج الذكاء الاصطناعي المحلية، حلل جداول Excel وملفات PDF فورياً، ابحث في الويب بدون هلوسة، وتحكم بالصوت.",
    "hero.downloadExe": "تحميل لنظام ويندوز",
    "hero.downloadExeSub": "ملف تثبيت Setup.exe · 8.9 ميغابايت · مجاني",
    "hero.otherVersions": "صيغ التحميل الأخرى",
    "hero.otherVersionsSub": "حزمة الشركات MSI والنسخة المحمولة",
    "stats.ram": "استهلاك الذاكرة",
    "stats.privacy": "خصوصية محلية",
    "stats.latency": "تأخير السحابة",
    "mockup.title": "AI Widget — الوضع الموسع (ChatGPT-Style)",
    "mockup.badge": "✓ نموذج Qwen 2.5 المحلي نشط",
    "mockup.userChip": "📎 جدول المقايسة والأسعار.xlsx (XLSX)",
    "mockup.userMsg": "هل يمكنك استخراج الإجمالي بدون ضريبة والمبلغ الإجمالي مع الضريبة من ملف Excel هذا؟",
    "mockup.botIntro": "إليك الملخص المالي المستخرج من جدول Excel المرفق:",
    "mockup.th1": "بيان الأعمال",
    "mockup.th2": "المبلغ بدون ضريبة",
    "mockup.th3": "نسبة الضريبة",
    "mockup.th4": "الإجمالي مع الضريبة",
    "mockup.row1_desc": "بند الأعمال الإنشائية",
    "mockup.row2_desc": "بند الكهرباء والتكييف",
    "mockup.total_label": "المجموع الكلي الإجمالي",
    "features.title": "لماذا تختار AI Widget؟",
    "features.desc": "مجموعة أدوات احترافية متكاملة لزيادة الإنتاجية وحماية البيانات الشخصية.",
    "f1.title": "100% محلي وبدون تسريب بيانات",
    "f1.desc": "مستنداتك ومحادثاتك لا تغادر جهازك أبداً. يعمل بالكامل دون الحاجة للاتصال بالإنترنت.",
    "f2.title": "تحليل شامل لملفات Excel و PDF",
    "f2.desc": "اسحب ملفات Excel أو Word أو PDF أو الصور (OCR). يستخرج الذكاء الاصطناعي الجداول والحسابات فورياً.",
    "f3.title": "بحث ويب ذكي وموثوق",
    "f3.desc": "محرك تصنيف ذكي يجلب الحقائق العامة المباشرة من مصادر موثوقة دون اختلاق معلومات.",
    "f4.title": "محادثة صوتية ذكية (Whisper + TTS)",
    "f4.desc": "تحدث بشكل طبيعي عبر محرك Whisper المدمج واستمع للردود بأصوات عصبية فائقة النقاء.",
    "f5.title": "عرض المعادلات الرياضية والمخططات",
    "f5.desc": "دعم كامل لصيغ LaTeX الرياضية ومخططات Mermaid البيانية التفاعلية.",
    "f6.title": "ملفات شخصية آمنة وترخيص مدى الحياة",
    "f6.desc": "بيئات مستخدمين معزولة، تشفير محلي في SQLite وترخيص دائم بدون اشتراكات شهرية.",
    "download.title": "تحميل AI Widget لنظام Windows",
    "download.desc": "متوافق مع Windows 10 و Windows 11 (64 بت). حجم خفيف للغاية.",
    "download.recommended": "موصى به",
    "download.setupTitle": "المثبت القياسي",
    "download.setupDesc": "تثبيت تلقائي وسريع مع إنشاء اختصارات سطح المكتب وقائمة ابدأ.",
    "download.btnExe": "📥 تحميل مباشر (.exe)",
    "download.msiTitle": "حزمة الشركات (MSI)",
    "download.msiDesc": "مثالية لمسؤولي الأنظمة والشبكات للتثبيت المركزي (GPO / SCCM).",
    "download.btnMsi": "📦 تحميل حزمة (.msi)",
    "download.portableTitle": "النسخة المحمولة (Portable)",
    "download.portableDesc": "برنامج مستقل يعمل فوراً دون الحاجة لتثبيت. جاهز للتشغيل من الفلاشة USB.",
    "download.btnPortable": "📂 تحميل النسخة المحمولة",
    "footer.tagline": "تم التطوير بكل شغف بواسطة <strong>S.H.A dev</strong>. جميع الحقوق محفوظة 2026.",
    "footer.contact": "📧 الدعم الفني والاستفسارات: s.h.a.dev.pro@gmail.com"
  }
};

function setLanguage(lang) {
  const dict = translations[lang] || translations.fr;
  document.documentElement.setAttribute('lang', lang);
  document.documentElement.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');

  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const key = el.getAttribute('data-i18n');
    if (dict[key]) {
      el.innerHTML = dict[key];
    }
  });

  document.querySelectorAll('.lang-btn').forEach((btn) => {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
  });
}

document.querySelectorAll('.lang-btn').forEach((btn) => {
  btn.addEventListener('click', () => {
    const lang = btn.getAttribute('data-lang');
    setLanguage(lang);
  });
});
