/**
 * AI Widget Showcase Website — Comprehensive 100% i18n & RTL Manager with Editions & Enterprise.
 */
const translations = {
  fr: {
    "nav.features": "Fonctionnalités",
    "nav.preview": "Aperçu",
    "nav.editions": "Éditions & Licences",
    "nav.download": "Télécharger",
    "nav.getApp": "Télécharger",
    "hero.tag": "100% Hors-Ligne & Données Sécurisées",
    "hero.title": "L'Intelligence Artificielle <br /><span class='gradient-text'>Directement sur votre Bureau</span>",
    "hero.subtitle": "Un widget discret, ultra-rapide et tout-en-un. Chattez avec vos modèles LLM locaux, analysez vos devis Excel et documents PDF en un clin d'œil, recherchez sur le Web sans hallucination, et pilotez tout à la voix.",
    "hero.downloadExe": "Télécharger pour Windows",
    "hero.downloadExeSub": "Setup.exe · 8.9 Mo · Gratuit",
    "hero.seeEditions": "Découvrir les Éditions",
    "hero.seeEditionsSub": "Standard · LITE · PRO Entreprise",
    "stats.ram": "Consommation RAM",
    "stats.privacy": "Confidentialité locale",
    "stats.latency": "Latence cloud",
    "mockup.title": "AI Widget — Mode Étendu (ChatGPT-Style)",
    "mockup.badge": "✓ Modèle Qwen 2.5 Local Actif",
    "mockup.userChip": "📎 Devis 40 logts.xlsx (XLSX)",
    "mockup.userMsg": "Peux-tu extraire le montant total HT et TTC de ce devis Excel ?",
    "mockup.botIntro": "Voici la synthèse financière extraite du tableau Excel joint :",
    "mockup.th1": "Désignation",
    "mockup.th2": "Montant HT",
    "mockup.th3": "Taux TVA",
    "mockup.th4": "Total TTC",
    "mockup.row1_desc": "Lot Gros Œuvre",
    "mockup.row2_desc": "Lot Électricité & CVC",
    "mockup.total_label": "MONTANT GLOBAL",
    "features.title": "Pourquoi choisir AI Widget ?",
    "features.desc": "Une suite d'outils ultra-puissants intégrés dans une interface ergonomique et intuitive.",
    "f1.title": "100% Local & Zéro Fuite",
    "f1.desc": "Vos documents, données et conversations ne quittent jamais votre machine. Fonctionne sans connexion Internet.",
    "f2.title": "Analyse Excel & PDF Universelle",
    "f2.desc": "Glissez vos fichiers .xlsx, .docx, .pdf ou scans OCR. L'IA extrait les tableaux, calcule les sommes et résume vos dossiers.",
    "f3.title": "Recherche Web Anti-Hallucination",
    "f3.desc": "Routeur d'intention intelligent qui recherche les faits publics en temps réel avec citation exacte des sources fiables.",
    "f4.title": "Chat Vocal Whisper & TTS",
    "f4.desc": "Parlez naturellement à votre assistant avec Whisper local et écoutez ses réponses avec des voix neuronales ultra-réalistes.",
    "f5.title": "Diagrammes Mermaid & LaTeX",
    "f5.desc": "Rendu vectoriel direct de formules mathématiques complexes et de diagrammes de flux interactifs.",
    "f6.title": "Licence & Multi-Profils Sécurisés",
    "f6.desc": "Gestion des profils isolés, chiffrement SQLite local et activation à vie sans abonnement mensuel.",
    "editions.badge": "💎 Gamme Complète",
    "editions.title": "Choisissez l'Édition Adaptée à Vos Besoins",
    "editions.desc": "De l'usage personnel quotidien au déploiement d'entreprise à grande échelle.",
    "editions.freeTitle": "Édition Standard",
    "editions.freeTarget": "Pour les particuliers & usage personnel",
    "editions.freePrice": "0 €",
    "editions.freePriceType": "Gratuit à vie",
    "editions.f_free1": "LLM 100% local (Llama.cpp & Ollama)",
    "editions.f_free2": "Chat rapide en bulle flottante & barre",
    "editions.f_free3": "Extraction de texte basique",
    "editions.f_free4": "Recherche Web anti-hallucination",
    "editions.f_free5": "Rendu Markdown & Formules LaTeX",
    "editions.btnFree": "Télécharger Gratuitement",
    "editions.liteBadge": "Professionnels",
    "editions.liteTitle": "Édition LITE",
    "editions.liteTarget": "Pour indépendants, cadres & experts",
    "editions.litePrice": "Licence Fixe",
    "editions.lifetime": "Activation à vie (HWID)",
    "editions.f_lite_all": "Tout ce qui est dans Standard, plus :",
    "editions.f_lite1": "Analyse avancée Excel multi-feuilles (.xlsx, .csv)",
    "editions.f_lite2": "Parsing Word (.docx) & PDF volumineux illimité",
    "editions.f_lite3": "Chat Vocal haute définition (Whisper + TTS)",
    "editions.f_lite4": "Vector DB & RAG sémantique local illimité",
    "editions.f_lite5": "Multi-profils isolés avec mot de passe & clé de secours",
    "editions.btnLite": "Activer la Licence LITE",
    "editions.proBadge": "Entreprise & Réseau",
    "editions.proTitle": "PRO Entreprise",
    "editions.proTarget": "PME, ETI, Cabinets & Administrateurs IT",
    "editions.proPrice": "Sur Mesure",
    "editions.proPriceType": "Déploiement Multipostes",
    "editions.f_pro_all": "Toutes les fonctionnalités LITE, plus :",
    "editions.f_pro1": "Package MSI (.msi) & Déploiement silencieux (GPO / SCCM)",
    "editions.f_pro2": "Politiques de Groupe IT & Verrouillage de conformité (Lockdown)",
    "editions.f_pro3": "Serveur IA Centralisé & RAG d'Entreprise partagé en réseau",
    "editions.f_pro4": "Console d'administration : gestion des utilisateurs & quotas",
    "editions.f_pro5": "Conformité RGPD On-Premise 100% étanche (Air-Gapped ready)",
    "editions.f_pro6": "Support technique dédié & accompagnement intégration",
    "editions.btnPro": "Contacter le Service Entreprise",
    "download.title": "Télécharger AI Widget pour Windows",
    "download.desc": "Compatible Windows 10 & Windows 11 (64-bit). Sans dépendance lourde.",
    "download.recommended": "Recommandé",
    "download.setupTitle": "Installateur Standard",
    "download.setupDesc": "Installation automatique avec raccourcis bureau et menu démarrer.",
    "download.btnExe": "📥 Télécharger (.exe)",
    "download.msiTitle": "Pack Entreprise (MSI)",
    "download.msiDesc": "Idéal pour les administrateurs système et déploiements réseau (GPO / SCCM).",
    "download.btnMsi": "📦 Télécharger (.msi)",
    "download.portableTitle": "Version Portable",
    "download.portableDesc": "Exécutable autonome sans aucune installation requise. Clé USB ready.",
    "download.btnPortable": "📂 Télécharger Portable",
    "footer.tagline": "Conçu avec passion par <strong>S.H.A dev</strong>. Tous droits réservés 2026.",
    "footer.contact": "📧 Support & Contact : s.h.a.dev.pro@gmail.com"
  },
  en: {
    "nav.features": "Features",
    "nav.preview": "Preview",
    "nav.editions": "Editions & Licenses",
    "nav.download": "Download",
    "nav.getApp": "Download",
    "hero.tag": "100% Offline & Private AI",
    "hero.title": "Artificial Intelligence <br /><span class='gradient-text'>Directly on your Desktop</span>",
    "hero.subtitle": "A discrete, lightning-fast all-in-one desktop assistant. Chat with local LLMs, analyze Excel spreadsheets and PDFs instantly, browse the web with zero hallucinations, and control everything by voice.",
    "hero.downloadExe": "Download for Windows",
    "hero.downloadExeSub": "Setup.exe · 8.9 MB · Free",
    "hero.seeEditions": "Explore Editions",
    "hero.seeEditionsSub": "Standard · LITE · PRO Enterprise",
    "stats.ram": "RAM Footprint",
    "stats.privacy": "Local Privacy",
    "stats.latency": "Cloud Latency",
    "mockup.title": "AI Widget — Expanded Mode (ChatGPT-Style)",
    "mockup.badge": "✓ Active Local Qwen 2.5 Model",
    "mockup.userChip": "📎 Construction Quote 40 Units.xlsx (XLSX)",
    "mockup.userMsg": "Can you extract total pre-tax and tax-included amounts from this Excel estimate?",
    "mockup.botIntro": "Here is the financial breakdown extracted from the attached spreadsheet:",
    "mockup.th1": "Designation",
    "mockup.th2": "Pre-Tax Amount",
    "mockup.th3": "VAT Rate",
    "mockup.th4": "Total Incl. Tax",
    "mockup.row1_desc": "Structural Works Lot",
    "mockup.row2_desc": "Electrical & HVAC Lot",
    "mockup.total_label": "OVERALL TOTAL",
    "features.title": "Why Choose AI Widget?",
    "features.desc": "A powerful local AI workspace designed for daily professional productivity.",
    "f1.title": "100% Local & Zero Data Leak",
    "f1.desc": "Your documents, prompts, and chats never leave your machine. Works completely offline.",
    "f2.title": "Universal Excel & PDF Analysis",
    "f2.desc": "Drag and drop .xlsx, .docx, .pdf or OCR scans. AI extracts tables, sums figures and drafts summaries.",
    "f3.title": "Anti-Hallucination Web Search",
    "f3.desc": "Smart intent classifier that fetches verified real-time public facts with cited sources.",
    "f4.title": "Whisper & Neural Voice Chat",
    "f4.desc": "Speak naturally with built-in local Whisper speech recognition and listen to neural voices.",
    "f5.title": "Mermaid & LaTeX Rendering",
    "f5.desc": "Instant vector rendering of complex math formulas and interactive workflow diagrams.",
    "f6.title": "Secure Profiles & Lifetime License",
    "f6.desc": "Isolated user workspaces, encrypted SQLite storage and lifetime activation with zero subscriptions.",
    "editions.badge": "💎 Complete Product Range",
    "editions.title": "Choose the Perfect Edition for Your Needs",
    "editions.desc": "From daily personal productivity to large-scale enterprise deployments.",
    "editions.freeTitle": "Standard Edition",
    "editions.freeTarget": "For individual & personal productivity",
    "editions.freePrice": "$0",
    "editions.freePriceType": "Lifetime Free",
    "editions.f_free1": "100% local LLM (Llama.cpp & Ollama)",
    "editions.f_free2": "Fast chat in floating bubble & compact bar",
    "editions.f_free3": "Basic document text extraction",
    "editions.f_free4": "Anti-hallucination web search",
    "editions.f_free5": "Markdown & LaTeX formulas rendering",
    "editions.btnFree": "Download Free",
    "editions.liteBadge": "Professionals",
    "editions.liteTitle": "LITE Edition",
    "editions.liteTarget": "For freelancers, executives & power users",
    "editions.litePrice": "One-Time License",
    "editions.lifetime": "Lifetime Activation (HWID)",
    "editions.f_lite_all": "Everything in Standard, plus:",
    "editions.f_lite1": "Advanced multi-sheet Excel parsing (.xlsx, .csv)",
    "editions.f_lite2": "Word (.docx) & large multi-page PDF processing",
    "editions.f_lite3": "High-Definition Voice Chat (Whisper + TTS)",
    "editions.f_lite4": "Unlimited local Vector DB & semantic RAG",
    "editions.f_lite5": "Isolated multi-profiles with master key & password",
    "editions.btnLite": "Activate LITE License",
    "editions.proBadge": "Enterprise & Network",
    "editions.proTitle": "PRO Enterprise",
    "editions.proTarget": "Companies, Teams & IT Administrators",
    "editions.proPrice": "Custom Quote",
    "editions.proPriceType": "Multi-Seat Deployment",
    "editions.f_pro_all": "Everything in LITE, plus:",
    "editions.f_pro1": "MSI package (.msi) & Silent Deployment (GPO / SCCM)",
    "editions.f_pro2": "Enterprise IT Policy & Security Lockdown enforcement",
    "editions.f_pro3": "Centralized Network LLM Server & Shared Corporate RAG",
    "editions.f_pro4": "Admin console: user quota management & access control",
    "editions.f_pro5": "100% On-Premise GDPR compliance (Air-Gapped ready)",
    "editions.f_pro6": "Dedicated technical support & integration assistance",
    "editions.btnPro": "Contact Enterprise Sales",
    "download.title": "Download AI Widget for Windows",
    "download.desc": "Compatible with Windows 10 & Windows 11 (64-bit). Ultra-lightweight.",
    "download.recommended": "Recommended",
    "download.setupTitle": "Standard Installer",
    "download.setupDesc": "Automatic setup with desktop and start menu shortcuts.",
    "download.btnExe": "📥 Download (.exe)",
    "download.msiTitle": "Enterprise Package (MSI)",
    "download.msiDesc": "Ideal for system administrators and corporate deployments (GPO / SCCM).",
    "download.btnMsi": "📦 Download (.msi)",
    "download.portableTitle": "Portable Edition",
    "download.portableDesc": "Standalone executable with zero installation needed. USB flash drive ready.",
    "download.btnPortable": "📂 Download Portable",
    "footer.tagline": "Built with passion by <strong>S.H.A dev</strong>. All rights reserved 2026.",
    "footer.contact": "📧 Support & Inquiries: s.h.a.dev.pro@gmail.com"
  },
  ar: {
    "nav.features": "المميزات",
    "nav.preview": "معاينة",
    "nav.editions": "الإصدارات والترخيص",
    "nav.download": "تحميل",
    "nav.getApp": "تحميل التطبيق",
    "hero.tag": "100% محلي وبدون إنترنت وحماية تامة",
    "hero.title": "الذكاء الاصطناعي الخارق <br /><span class='gradient-text'>مباشرة على سطح مكتبك</span>",
    "hero.subtitle": "أداة سطح مكتب أنيقة وسريعة للغاية. تحدث مع نماذج الذكاء الاصطناعي المحلية، حلل جداول Excel وملفات PDF فورياً، ابحث في الويب بدون هلوسة، وتحكم بالصوت.",
    "hero.downloadExe": "تحميل لنظام ويندوز",
    "hero.downloadExeSub": "ملف تثبيت Setup.exe · 8.9 ميغابايت · مجاني",
    "hero.seeEditions": "استكشف الإصدارات",
    "hero.seeEditionsSub": "القياسي · LITE · PRO للمؤسسات",
    "stats.ram": "استهلاك الذاكرة",
    "stats.privacy": "خصوصية محلية",
    "stats.latency": "تأخير السحابة",
    "mockup.title": "AI Widget — الوضع الموسع (ChatGPT-Style)",
    "mockup.badge": "✓ نموذج Qwen 2.5 المحلي نشط",
    "mockup.userChip": "📎 جدول المقايسة والأسعار.xlsx (XLSX)",
    "mockup.userMsg": "هل يمكنك استخراج الإجمالي بدون ضريبة والمبلغ الإجمالي مع الضريبة من ملف Excel هذا؟",
    "mockup.botIntro": "إليك الملخص المالي المستخرج من جدول Excel المرفق:",
    "mockup.th1": "بيان الأعمال",
    "mockup.th2": "المبلغ بدون ضريبة",
    "mockup.th3": "نسبة الضريبة",
    "mockup.th4": "الإجمالي مع الضريبة",
    "mockup.row1_desc": "بند الأعمال الإنشائية",
    "mockup.row2_desc": "بند الكهرباء والتكييف",
    "mockup.total_label": "المجموع الكلي الإجمالي",
    "features.title": "لماذا تختار AI Widget؟",
    "features.desc": "مجموعة أدوات احترافية متكاملة لزيادة الإنتاجية وحماية البيانات الشخصية.",
    "f1.title": "100% محلي وبدون تسريب بيانات",
    "f1.desc": "مستنداتك ومحادثاتك لا تغادر جهازك أبداً. يعمل بالكامل دون الحاجة للاتصال بالإنترنت.",
    "f2.title": "تحليل شامل لملفات Excel و PDF",
    "f2.desc": "اسحب ملفات Excel أو Word أو PDF أو الصور (OCR). يستخرج الذكاء الاصطناعي الجداول والحسابات فورياً.",
    "f3.title": "بحث ويب ذكي وموثوق",
    "f3.desc": "محرك تصنيف ذكي يجلب الحقائق العامة المباشرة من مصادر موثوقة دون اختلاق معلومات.",
    "f4.title": "محادثة صوتية ذكية (Whisper + TTS)",
    "f4.desc": "تحدث بشكل طبيعي عبر محرك Whisper المدمج واستمع للردود بأصوات عصبية فائقة النقاء.",
    "f5.title": "عرض المعادلات الرياضية والمخططات",
    "f5.desc": "دعم كامل لصيغ LaTeX الرياضية ومخططات Mermaid البيانية التفاعلية.",
    "f6.title": "ملفات شخصية آمنة وترخيص مدى الحياة",
    "f6.desc": "بيئات مستخدمين معزولة، تشفير محلي في SQLite وترخيص دائم بدون اشتراكات شهرية.",
    "editions.badge": "💎 باقات متكاملة",
    "editions.title": "اختر الإصدار المناسب لاحتياجاتك",
    "editions.desc": "من الاستخدام الفردي اليومي إلى النشر المؤسسي والشبكي واسع النطاق.",
    "editions.freeTitle": "الإصدار القياسي (Standard)",
    "editions.freeTarget": "للأفراد والاستخدام الشخصي اليومي",
    "editions.freePrice": "0 $",
    "editions.freePriceType": "مجاني مدى الحياة",
    "editions.f_free1": "تشغيل نماذج الذكاء الاصطناعي محلياً 100%",
    "editions.f_free2": "محادثة سريعة عبر الفقاعة العائمة والشريط",
    "editions.f_free3": "استخراج نصوص المستندات الأساسي",
    "editions.f_free4": "بحث ويب ذكي مع توثيق المصادر",
    "editions.f_free5": "عرض تنسيقات Markdown ومعادلات LaTeX",
    "editions.btnFree": "تحميل الإصدار المجاني",
    "editions.liteBadge": "للمحترفين",
    "editions.liteTitle": "إصدار LITE الاحترافي",
    "editions.liteTarget": "للمستقلين، الاستشاريين والخبراء",
    "editions.litePrice": "ترخيص ثابت",
    "editions.lifetime": "تفعيل دائم مدى الحياة (HWID)",
    "editions.f_lite_all": "يشمل جميع مزايا الإصدار القياسي، بالإضافة إلى:",
    "editions.f_lite1": "تحليل متقدم لجداول Excel متعددة الأوراق (.xlsx)",
    "editions.f_lite2": "معالجة غير محدودة لملفات Word (.docx) و PDF الكبيرة",
    "editions.f_lite3": "محادثة صوتية عالية الدقة (Whisper + نطق عصبي)",
    "editions.f_lite4": "قاعدة بيانات متجهات RAG سيمانتك محلية غير محدودة",
    "editions.f_lite5": "ملفات مستخدمين معزولة مع كلمة سر ومفتاح استرجاع",
    "editions.btnLite": "تفعيل ترخيص LITE",
    "editions.proBadge": "للشركات والشبكات",
    "editions.proTitle": "PRO Enterprise للشركات",
    "editions.proTarget": "للشركات والمؤسسات ومسؤولي تكنولوجيا المعلومات",
    "editions.proPrice": "عرض مخصص",
    "editions.proPriceType": "نشر متعدد الأجهزة",
    "editions.f_pro_all": "يشمل جميع مزايا LITE، بالإضافة إلى:",
    "editions.f_pro1": "حزمة MSI (.msi) وتثبيت صامت عبر الشبكة (GPO / SCCM)",
    "editions.f_pro2": "سياسات المجموعة وقفل الأمان المؤسسي (IT Policies & Lockdown)",
    "editions.f_pro3": "خادم ذكاء اصطناعي مركزي ومكتبة معرفية RAG مشتركة",
    "editions.f_pro4": "لوحة تحكم المدير: إدارة المستخدمين وحصص الاستهلاك (Quotas)",
    "editions.f_pro5": "مطابقة تامة لخصوصية البيانات On-Premise بدون اتصال خارجي",
    "editions.f_pro6": "دعم فني مخصص ومساعدة كاملة في النشر والتكامل",
    "editions.btnPro": "طلب عرض للشركات",
    "download.title": "تحميل AI Widget لنظام Windows",
    "download.desc": "متوافق مع Windows 10 و Windows 11 (64 بت). حجم خفيف للغاية.",
    "download.recommended": "موصى به",
    "download.setupTitle": "المثبت القياسي",
    "download.setupDesc": "تثبيت تلقائي وسريع مع إنشاء اختصارات سطح المكتب وقائمة ابدأ.",
    "download.btnExe": "📥 تحميل مباشر (.exe)",
    "download.msiTitle": "حزمة الشركات (MSI)",
    "download.msiDesc": "مثالية لمسؤولي الأنظمة والشبكات للتثبيت المركزي (GPO / SCCM).",
    "download.btnMsi": "📦 تحميل حزمة (.msi)",
    "download.portableTitle": "النسخة المحمولة (Portable)",
    "download.portableDesc": "برنامج مستقل يعمل فوراً دون الحاجة لتثبيت. جاهز للتشغيل من الفلاشة USB.",
    "download.btnPortable": "📂 تحميل النسخة المحمولة",
    "footer.tagline": "تم التطوير بكل شغف بواسطة <strong>S.H.A dev</strong>. جميع الحقوق محفوظة 2026.",
    "footer.contact": "📧 الدعم الفني والاستفسارات: s.h.a.dev.pro@gmail.com"
  }
};

function setLanguage(lang) {
  const dict = translations[lang] || translations.fr;
  document.documentElement.setAttribute('lang', lang);
  document.documentElement.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');

  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const key = el.getAttribute('data-i18n');
    if (dict[key]) {
      el.innerHTML = dict[key];
    }
  });

  document.querySelectorAll('.lang-btn').forEach((btn) => {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
  });
}

document.querySelectorAll('.lang-btn').forEach((btn) => {
  btn.addEventListener('click', () => {
    const lang = btn.getAttribute('data-lang');
    setLanguage(lang);
  });
});
